[package]
name = "brawlhalla-replay-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
brparser = { path = "brparser" }
clap = { version = "4.5.40", features = ["derive"] }
serde_json = "1.0.140"